### PR TITLE
Fix "One or more selected network interfaces is not configured"

### PR DESCRIPTION
**Pull request by mvidner**
https://bugzilla.opensuse.org/show_bug.cgi?id=958525

### CODE REVIEW

**Comment by mvidner** [comment]
Works for me, but let's wait for @mcaj's feedback before merging.

**Comment by jreidinger** [comment]
@mvidner what is status here?

**Comment by mvidner** [comment]
Made mergeable.

**Comment by jreidinger** [comment]
LGTM

**Pull request merged**
