### PR TITLE
IsDNSZoneMaintained returns inverted value

### PR DESCRIPTION
**Pull request by obel1x**
IsDNSZoneMaintained returns inverted value, leading to not working "Synchronise DNS-Server"

### CODE REVIEW

**Comment by dgdavid** [comment]
@obel1x thanks a ton for your contribution! At first glance, it looks reasonable to me.

But in order to get it merged, we need to update the version and changelog (see https://yastgithubio.readthedocs.io/en/latest/contributing/#code-changes) and ideally add a small unit test for touched code in https://github.com/yast/yast-dhcp-server/blob/master/test/dialog_test.rb.

We can proceed as you want: you try to do it by yourself and we review it, or I can help with it for moving it on if you're busy.

**Comment by obel1x** [comment]
great, thanks! i have had a quick look at those unit tests. ruby looks like a beautiful language, but as i am not used to it and also would not know how the test should look processual, i think it should be better done by you.

A complete test could create a dns- domain, insert values in it, checking if it had been created completely and remove it afterwards. But this is far to complex for me i guess.

**Comment by dgdavid** [comment]
> ... i think it should be better done by you.
> 
> Also currently i do not have a local copy with rake and osc installed, this was done on github directly. So please can you also do the version changes and changelogs?

Sure, no problem. Added to my to-do list :)

Thanks

**Review by imobachgs — APPROVED** [review]

**Comment by dgdavid** [comment]
Merged! Thanks a lot @obel1x!

**Pull request merged**
